<?php

namespace Kommercio\Listeners;

use Kommercio\Events\CouponEvent;
use Kommercio\Models\PriceRule\Coupon;

class CouponListener
{
    public $coupon;

    /**
     * Handle the event.
     *
     * @param  CouponEvent  $event
     * @return void
     */
    public function handle(CouponEvent $event)
    {
        $type = $event->type;
        $this->coupon = $event->coupon;

        if($type == 'used') {
            $this->onUsed();
        }
    }

    /**
     * Do something on coupon used
     * @return void
     */
    protected function onUsed()
    {
        //If coupon is generated by reward redemption, mark is as reward used
        if($this->coupon->redemption){
            $this->coupon->markRewardUsed();
        }
    }
}
